### ISSUE TITLE
Allow lib to still function without shims / shams?

### ISSUE THREAD

**Issue by glenjamin** [Xotic750/inspect-x#43]
Hello! This module looks great, I was looking for a version of `util.inspect` that'll run in the browser, and has wide datatype support, so this is perfect.

In the docs you mention the shims and shams - looking at the code there's a few guards in place for when they're not present - but not everything is guarded.

Do you have defined minimum version in mind? Would you be open to a PR which allowed the lib to load and run in ES5 environments without breaking - while keeping the level of support for other datatypes it already has?

From a cursory look this would just be using ponyfill libs for the following three functions:

```js
  var $ownKeys = Reflect.ownKeys;
  var $is = Object.is;
  var $assign = Object.assign;
```

**Comment by Xotic750** [comment]
Hi @glenjamin I originally wrote all my modules using ponyfills, then I started to notice some deficiencies in some of the code that I was requiring.
 I investigated and found that it was best to use the ES shims as they were accurate (as accurate as can be), I removed the ponyfills and made the decision to write my code using ES5 and ES6 but to be as conservative as possible and use only methods that were shimmable, and avoid new syntax like arrow functions etc.
 Removing such requires has meant that the code base has been reduced by over half while remaining, in the most, compatible with ES3 only engines. Besides, nearly every environment that I have tested has bugs in either the ES5 or ES6 implementation, using the ES shims fixes these issues for me without any need to worry, and I load theses in all my projects or work that I do, and I recommend them to all.
I don't think it would be wise to back out of this decision and changes, I have created numerous modules that are required by this project, and they have all been written in a similar manner, i.e. requiring the ES shims. If you were to back out this project, then it is likely that you would also need to do the same with all of those too.

Some shims are available as stand-alones, if loading the full shim is a problem (I don't know why you wouldn't load them)?
https://github.com/ljharb/object-is
https://github.com/ljharb/object.assign

Reflect.ownkeys which is just
```
Object.getOwnPropertyNames(target).concat(Object.getOwnPropertySymbols(target)).
```
but
```
Object.getOwnPropertyNames
```
and especially
```
Object.getOwnPropertySymbols
```
are not shimmable, and you would have to guard (ES5 shim uses `Object.keys` for `Object.getOwnPropertyNames`)

Other modules that I require use 
```
Object.getPrototypeOf
```
and
```
Object.getOwnPropertyDescriptor
```
Which again are not supported by all browsers and are only partially shimmable accurately, but most use cases are covered.

So back to just ES5 only (yes, I would say that ES5 is my minimum target), those ES6 methods
```
  var $ownKeys = Reflect.ownKeys;
  var $is = Object.is;
  var $assign = Object.assign;
```
Are fairly easy to replace with ES5 equivalents, though it would seem a shame to not use ES6 methods, especially with ES7 just around the corner. I will give it a little reconsideration.

**Comment by glenjamin** [comment]
I'm generally happy to use ES6 shims in my applications, but I'd like to not hard-require consumers of my libraries with this.

I've published a simple ponyfill for Reflect.ownKeys - https://github.com/glenjamin/Reflect.ownKeys

Using this makes this lib load without throwing on the current version of Node.js

My personal preference at the moment is to work without forcing a consumer to globally polyfill on ES5, but require polyfills for ES3 environments - and to detect & make use of ES6 features if they exist

**Comment by Xotic750** [comment]
Changes were made.
